language: python
python:
- '3.7'
install:
- pip install -r requirements.txt
script:
- make flake
- make test
- make build
deploy:
  provider: pypi
  user: __token__
  password:
    secure: "D6Z0GxnuJL4J85/TKE+M/ifs26esmD/gxWFjeTez1tWOvCufInGhm0aa2Vo50KvqmyVxzSVpFJH+TXj+TjPCVLJYBwrUYTBRgpbXL9UPDLAgBp1454ZASAdQeMFUrvw0ayrwOvL83r/iyOojvbP2Lvv/e2Kst0adYVVSm5E9V3TbUIVW8GrI9OmXCxsM58nHcT68tPABtNaXvA/dRyH8DiKOmju9ULLrT9G9jiiXOdY8/6F8FzXCupxSHVwasrlG1ctItSPtMPYHD4e67EU+PdeYoCMSmaeiJmbMv6kIlUc//dY9IcD+oKKJyGvbjLw5v4Kiwof17ndNvxcosgXEAoxpsAk/kME+M6MglN/Jw5jXaWgqJTFkNpeVUwjU3owBImSAAjXvrkzlM302VTzaA5L/26/KxeeZWD2OOZPgBCZ4ohA84d+nvcNWLudQoM1XeplZ2fRz5vrPga8d3mcpg6KGKkJc+TCmw+H/0vdfEa5Q/jwHRpX3yuDwb8gnA5RgE/2Zl21m/W2ZYinDLcMQXIh7+VtMpFAOpn4fBHEWIY/D5pn/UttmIkwczePJeOUZky9pqYdboPKhKjXVQE8mWcwdZeK6S3ytGt++lHWMj5pjGIGD9zhFo+ooTF/PriJuYfzEpugD/8gBRre+PPnl9d+5Sd7YNPiwwnJ23iHNw+Y="
sudo: required
addons:
  apt:
    packages:
    - libcurl4-openssl-dev
    - libelf-dev
    - libdw-dev
    - cmake
after_success: bash <(curl -s https://codecov.io/bash)
