language: python
python:
  - "3.7"
install:
  - pip install -r requirements.txt
# run linting and tests
script:
  - make flake
  - make test

sudo: required

addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - cmake

after_success: |
  bash <(curl -s https://codecov.io/bash)